-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 10:15:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_livro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_livro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_livro` DEFAULT CHARACTER SET utf8 ;
USE `db_livro` ;

-- -----------------------------------------------------
-- Table `db_livro`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_livro`.`GENERO` (
  `gen_codigo` INT NOT NULL AUTO_INCREMENT,
  `gen_descricao` VARCHAR(100) NOT NULL,
  `gen_ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`gen_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_livro`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_livro`.`AUTOR` (
  `aut_codigo` INT NOT NULL AUTO_INCREMENT,
  `aut_nome` VARCHAR(100) NOT NULL,
  `aut_ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`aut_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_livro`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_livro`.`LIVRO` (
  `liv_codigo` INT NOT NULL AUTO_INCREMENT,
  `liv_isbn` CHAR(17) NOT NULL,
  `liv_titulo` VARCHAR(200) NOT NULL,
  `gen_codigo` INT NOT NULL,
  `aut_codigo` INT NOT NULL,
  `liv_disponivel` CHAR(1) NOT NULL,
  `liv_ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`liv_codigo`),
  INDEX `fk_gen_codigo_idx` (`gen_codigo` ASC) VISIBLE,
  INDEX `fk_LIVRO_AUTOR1_idx` (`aut_codigo` ASC) VISIBLE,
  UNIQUE INDEX `liv_isbn_UNIQUE` (`liv_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_gen_codigo`
    FOREIGN KEY (`gen_codigo`)
    REFERENCES `db_livro`.`GENERO` (`gen_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_AUTOR1`
    FOREIGN KEY (`aut_codigo`)
    REFERENCES `db_livro`.`AUTOR` (`aut_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_livro`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_livro`.`USUARIO` (
  `usu_login` CHAR(11) NOT NULL,
  `usu_nome` VARCHAR(100) NOT NULL,
  `usu_email` VARCHAR(100) NULL,
  `usu_senha` VARCHAR(60) NOT NULL,
  `usu_administrador` CHAR(1) NOT NULL,
  `usu_ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`usu_login`),
  UNIQUE INDEX `usu_email_UNIQUE` (`usu_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_livro`.`LOCACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_livro`.`LOCACAO` (
  `loc_codigo` INT NOT NULL AUTO_INCREMENT,
  `liv_codigo` INT NOT NULL,
  `usu_login` CHAR(11) NOT NULL,
  `loc_data_locacao` DATETIME NOT NULL,
  `loc_data_previsao_retorno` DATETIME NOT NULL,
  `loc_data_devolucao` DATETIME NOT NULL,
  `loc_ativa` CHAR(1) NOT NULL,
  PRIMARY KEY (`loc_codigo`),
  INDEX `fk_LOCACAO_LIVRO1_idx` (`liv_codigo` ASC) VISIBLE,
  INDEX `fk_LOCACAO_USUARIO1_idx` (`usu_login` ASC) VISIBLE,
  CONSTRAINT `fk_LOCACAO_LIVRO1`
    FOREIGN KEY (`liv_codigo`)
    REFERENCES `db_livro`.`LIVRO` (`liv_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCACAO_USUARIO1`
    FOREIGN KEY (`usu_login`)
    REFERENCES `db_livro`.`USUARIO` (`usu_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
